apiVersion: batch/v1
kind: Job
metadata:
  name: function-register-job
  namespace: ndn
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  labels:
    app: function-register
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 180
  template:
    metadata:
      labels:
        app: function-register
    spec:
      restartPolicy: Never
      containers:
        - name: registerer
          image: ghcr.io/nakazato-lab/ndn-tools-seed-python/ndn-function-sidecar:latest
          imagePullPolicy: Always
          command: ["python", "-u", "/scripts/function_register.py"]
          env:
            - name: FUNCTION_PATH
              value: /functions/average.ndn
            - name: NFD_CONFIG_PATH
              value: /etc/ndn-config/ADDRESS
            - name: MANAGER_REGISTER_NAME
              value: /Manager/register
          volumeMounts:
            - name: register-script
              mountPath: /scripts
              readOnly: true
            - name: function-source
              mountPath: /functions
              readOnly: true
            - name: nfd-endpoint
              mountPath: /etc/ndn-config
              readOnly: true
      volumes:
        - name: register-script
          configMap:
            name: function-register-script
        - name: function-source
          configMap:
            name: function-register-source
        - name: nfd-endpoint
          configMap:
            name: nfd-config
            optional: false
