apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ndn

resources:
  - ../conf
  - nfd.yaml
  - seed-rbac.yaml
  - seed.yaml
  - spy-rbac.yaml
  - spy.yaml
  - manager-rbac.yaml
  - manager.yaml
  - function-register.yaml
  - function-invoke.yaml
