apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ndn

resources:
  - nfd.yaml
  - seed-rbac.yaml
  - seed.yaml
  - spy-rbac.yaml
  - spy.yaml
  - manager-rbac.yaml
  - manager.yaml
  - function-register.yaml
  - function-invoke.yaml

configMapGenerator:
  - name: function-invoke-script
    files:
      - function_invoke.py=scripts/function_invoke.py
  - name: function-register-script
    files:
      - function_register.py=scripts/function_register.py
  - name: function-register-source
    files:
      - average.ndn=functions/average.ndn
