apiVersion: v1
kind: Service
metadata:
  name: nfd-service
  namespace: ndn # ★ ご自身の環境に合わせる
spec:
  selector:
    app: nfd # ★ NFDのPodに付いているラベルを指定
  ports:
    - name: ndn-tcp
      protocol: TCP
      port: 6363
      targetPort: 6363
