apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: seed-daemonset
  labels:
    app: seed
spec:
  selector:
    matchLabels:
      app: seed
  template:
    metadata:
      labels:
        app: seed
    spec:
      serviceAccountName: seed-service-account
      # nfd待機用initContainers 検討
      containers:
        - name: seed
          image: ryotaroiwata/ndn-seed:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command: ["/bin/bash", "-c"]
          # NFDのソケットができるまで待機してからSeedを起動
          args:
            - |
              NFD_IP=$(cat /etc/nfd-config/ADDRESS)
              export NDN_CLIENT_TRANSPORT="tcp4://${NFD_IP}:6363"
              echo "Connecting to NFD at ${NDN_CLIENT_TRANSPORT}..."
              ndnseed --namespace ndn /${NODE_NAME}/seed/
          volumeMounts:
            - name: nfd-config
              mountPath: /etc/nfd-config
      volumes:
        - name: nfd-config
          configMap:
            name: nfd-config
            optional: false
